@startuml
right header
<font size=24 color=black>Package: <b>UCD_1.1
end header

title
<font size=18 color=black>База данних маганзину одягу
<font size=16 color=black>Діаграма прецедентів
end title

actor "Гість" as Guest
actor "Користувач" as User
actor "Адміністратор" as Admin

' UCes for Guest:
usecase "<b>UC_1</b>\nРеєстрація" as UC1_Guest
usecase "<b>UC_2</b>\nПерегляд вмісту" as UC2_Guest
usecase "<b>UC_3</b>\nАвторизація" as UC3_Guest



' UCes for User:
usecase "<b>UC_1</b>\nДодавання або віднімання\nтовару" as UC1_User
usecase "<b>UC_2</b>\nВідстежування місцерозташування\nтовару" as UC2_User
usecase "<b>UC_3</b>\nЗв'язок з адміністратором" as UC3_User


' UCes for Admin:
usecase "<b>UC_1</b>\nОбробка звернень користувача" as UC1_Admin
usecase "<b>UC_2</b>\nМаніпуляції з правами\nдоступу користувачів" as UC2_Admin


' Actors connections
User -u-|> Guest

Admin -u--|> User


' UCes connectios
Guest -u-> UC1_Guest
Guest -u-> UC2_Guest
Guest -u-> UC3_Guest



User -u-> UC1_User
User -u-> UC2_User
User -u--> UC3_User


Admin -d--> UC1_Admin
Admin -d-> UC2_Admin


right footer
База данних магазину одягу. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
