@startuml
left header
<font color=000 size=18><b>Package:</b> User

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Додавання або віднімання товару.
<font color=000 size=16><b>Учасники:</b> Користувач, Система.
<font color=000 size=16><b>Передумови:</b> Користувач авторизований в системі.
<font color=000 size=16><b>Результат:</b> Користувач зберіг товар або удалив його.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Доступ до бази даних відсутній

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
:  Користувач додає товар або користувач видаляє товар;

|Система|
: Система вимагає пітвердження від користувача;

|Користувач|
: Користувач підтверджує або відміняє дію;

|Система|
: При підтвердженні, система додає або видаляє товар з бажаних;
note right #aaffaa

<font color=red><b> Можливо EX_00.

end note

|Користувач|
stop;

right footer

Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
