@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b>  Обробка звернень користувача.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Користувач написав на електронну пошту адміністратору.
<font color=000 size=16><b>Результат:</b> Відповідь користовачу.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить у розділ "Звернення користувачів";

|Система|
: Система надає адміністратору інформацію про звернення користувачів;

|Користувач|
: Адміністратор вибирає звернення окремого користувача;

|Система|
: Система надає адміністратору повідомлення користувача;

|Користувач|
: Адміністратор відповідає користувачу;

|Система|
: Система надсилає відповідь користувачу;

|Користувач|

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
