@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-2
<font color=000 size=16><b>Назва:</b>  Маніпуляції з правами доступу користувачів.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Користувачі мають бути наявні в системі.
<font color=000 size=16><b>Результат:</b> Зміна прав доступу функцій окремого користувача.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить у розділ "Користувачі";

|Система|
: Система показує всіх наявних користувачів;

|Користувач|
: Адміністратор обирає необхідного користувача;

|Система|
: Система надає можливості взаємодії обраного користувача
 з його функціями;

|Користувач|
: Адміністратор ставить/знімає галочки поруч з пунктами
 додавання або віднімання товару, зв'язку з адміністрацією,
 замовлення за його номером телефону, відстеження місцезнаходження
 товару, також наявна можливість "Забрати доступ", що значить бан
 (можна вказати причину бану) або ж видалення;

note left #aaffaa
"Забрати доступ" - значить бан
(можна вказати причину бану)
або ж видалення.
end note

|Система|
: Система реагує на обрані адміністратором права доступу та змінює
 можливості користувача;

|Користувач|
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
