@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b>  Можливість "відігравати роль" користувача.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор повинен перевірити місцезнаходження товару або обробити заявку.
<font color=000 size=16><b>Результат:</b> Оброблене замовлення або інформація щодо місцеположення товару.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить у розділ "Вхідні заявки";

|Система|
: Система надає адміністратору інформацію щодо необроблених заявок;

|Користувач|
: Адміністратор вибирає замовлення;

|Система|
: Система надає адміністратору інформацію про замовлення

: Система телефонує на номер замовника;

|Користувач|
: Адміністратор підтверджує або ж відхиляє замовлення;

|Система|
: Система змінює дані (добавляє товару власника);

|Користувач|
: Адміністратор заходить у розділ "[Назва товару]" -> "Відстежування";

|Система|
: Система надає адміністратору інформацію щодо місцеположення товару;

|Користувач|

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
